import * as THREE from "three";
import landDots from "../../data/land-dots.json";
import { guessViewerLatLng } from "./tz-coords";

// GitHub-homepage-style globe, recolored for the Azerit light theme: a halftone
// dot globe (one dot per land grid cell, generated by scripts/generate-globe-dots.mjs)
// with animated arcs firing between random land points. Auto-rotates, drag to
// spin. Lives in its own chunk — HeroGlobe dynamic-imports this module so
// three.js never lands in the main bundle.

const R = 1;
// far enough back that the tallest arc trajectories (~1.25R from center) stay
// inside the frustum instead of clipping at the canvas edge
const CAMERA_Z = 5.15;
const AUTO_SPIN = 0.032; // rad/s
const MAX_TILT = 0.55; // vertical drag clamp
const ARC_COUNT = 7;
const ARC_SEGMENTS = 64;
const ARC_INDEX_COUNT = ARC_SEGMENTS * 6 * 6; // tubularSegments * radialSegments * 2 tris
const BEAM_COUNT = 14; // light pillars rising from the surface

// brand ramp (teal -> chartreuse), same family as the rest of the page.
// kept dark: light teals wash out on the white page background.
const DOT_COLORS = ["#0a5c55", "#0f766e", "#1c8577", "#2f9e8c"];
const DOT_LIME = "#7a8a1f";
const ARC_COLORS = ["#0d9488", "#10a394", "#0f766e", "#7a8a1f"];
const BEAM_TIP = "#0a4f49";
const RIM_COLOR = "#14b8a6";

// screen-fixed "sun" from the top left, github style: the lit crescent stays
// put while the globe spins under it. View-space, shared by all shaders.
const LIGHT_DIR = new THREE.Vector3(-0.5, 0.55, 0.42).normalize();

function latLngToVec3(lat: number, lng: number, radius: number) {
  const phi = (lat * Math.PI) / 180;
  const lambda = (lng * Math.PI) / 180;
  return new THREE.Vector3(
    radius * Math.cos(phi) * Math.cos(lambda),
    radius * Math.sin(phi),
    -radius * Math.cos(phi) * Math.sin(lambda)
  );
}

// vertical alpha gradient: beams are solid at the surface, fade toward the tip
function makeBeamTexture() {
  const c = document.createElement("canvas");
  c.width = 4;
  c.height = 64;
  const ctx = c.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 64, 0, 0); // canvas bottom = uv 0 = beam base
  g.addColorStop(0, "rgba(255,255,255,1)");
  g.addColorStop(0.45, "rgba(255,255,255,0.7)");
  g.addColorStop(1, "rgba(255,255,255,0)");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 4, 64);
  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  return tex;
}

// deterministic pseudo-random, same trick as the old Graph3D
function seeded(n: number) {
  const x = Math.sin(n * 127.1 + 311.7) * 43758.5453;
  return x - Math.floor(x);
}

type Arc = {
  mesh: THREE.Mesh<THREE.TubeGeometry, THREE.MeshBasicMaterial>;
  pulses: THREE.Mesh<THREE.RingGeometry, THREE.MeshBasicMaterial>[];
  a: THREE.Vector3;
  b: THREE.Vector3;
  start: number; // ms timestamp the draw phase begins
  draw: number; // ms to draw head A -> B
  hold: number; // ms fully drawn
  erase: number; // ms to retract tail
  gap: number; // ms idle before respawn
  startPulsed: boolean;
  endPulsed: boolean;
};

export function initGlobe(container: HTMLElement): () => void {
  let renderer: THREE.WebGLRenderer;
  try {
    renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  } catch {
    return () => {}; // no WebGL: leave the CSS halo as a quiet fallback
  }
  renderer.setClearColor(0x000000, 0);
  container.appendChild(renderer.domElement);

  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(28, 1, 0.1, 20);
  camera.position.set(0, 0, CAMERA_Z);
  const render = () => renderer.render(scene, camera);

  // tilt (outer, holds the axis + vertical drag) -> spin (inner, rotates on Y)
  const tilt = new THREE.Group();
  const spin = new THREE.Group();
  tilt.add(spin);
  scene.add(tilt);
  // Start centered on the visitor's region, guessed from their time zone.
  // We rotate the target point onto the +Z axis (facing the camera): spin.y
  // brings its longitude to the front meridian, then tilt.x lifts its latitude
  // to the equator line. tilt.z is a pure roll around the view axis, so it
  // leaves a front-centered point put — kept for the same aesthetic lean.
  const viewer = guessViewerLatLng();
  const target = latLngToVec3(viewer.lat, viewer.lng, R);
  tilt.rotation.z = -0.16;
  spin.rotation.y = Math.atan2(-target.x, target.z);
  // clamp to the same envelope the vertical drag uses (MAX_TILT). Beyond it the
  // globe tips too pole-on — and, crucially, going past it here would make the
  // first drag snap the tilt back into range, a visible jump on first touch.
  tilt.rotation.x = THREE.MathUtils.clamp((viewer.lat * Math.PI) / 180, -MAX_TILT, MAX_TILT);

  // inner sphere: occludes far-side dots so the halftone reads as a solid
  // globe, shaded by the screen-fixed light for a sense of volume.
  // NB: every custom shader here ends with <colorspace_fragment> — without it
  // the linear-space colors are written raw to the sRGB canvas and wash out.
  const sphereMat = new THREE.ShaderMaterial({
    uniforms: {
      uLight: { value: LIGHT_DIR },
      uLit: { value: new THREE.Color("#ffffff") },
      uShadow: { value: new THREE.Color("#d7e9e4") },
    },
    vertexShader: `
      varying vec3 vN;
      void main() {
        vN = normalize(normalMatrix * normal);
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
    fragmentShader: `
      uniform vec3 uLight;
      uniform vec3 uLit;
      uniform vec3 uShadow;
      varying vec3 vN;
      void main() {
        float l = clamp(dot(normalize(vN), uLight), 0.0, 1.0);
        gl_FragColor = vec4(mix(uShadow, uLit, l), 1.0);
        #include <colorspace_fragment>
      }
    `,
  });
  const sphere = new THREE.Mesh(new THREE.SphereGeometry(R * 0.99, 64, 64), sphereMat);
  spin.add(sphere);

  // glowing rim: a slightly larger back-side shell whose alpha peaks at the
  // silhouette (fresnel), so the globe's contour reads as a bright teal ring.
  // NB: alpha blending, not additive — additive is invisible on a white page.
  const rimMat = new THREE.ShaderMaterial({
    transparent: true,
    depthWrite: false,
    side: THREE.BackSide,
    uniforms: {
      uColor: { value: new THREE.Color(RIM_COLOR) },
      uLight: { value: LIGHT_DIR },
    },
    vertexShader: `
      uniform vec3 uLight;
      varying float vRim;
      varying float vFace;
      void main() {
        vec4 mv = modelViewMatrix * vec4(position, 1.0);
        vec3 n = normalize(normalMatrix * normal);
        vRim = pow(1.0 - abs(dot(n, normalize(-mv.xyz))), 5.0);
        vFace = clamp(dot(n, uLight), 0.0, 1.0);
        gl_Position = projectionMatrix * mv;
      }
    `,
    fragmentShader: `
      uniform vec3 uColor;
      varying float vRim;
      varying float vFace;
      void main() {
        gl_FragColor = vec4(uColor, vRim * mix(0.05, 1.0, vFace));
        #include <colorspace_fragment>
      }
    `,
  });
  const rim = new THREE.Mesh(new THREE.SphereGeometry(R * 1.035, 64, 64), rimMat);
  rim.renderOrder = 3;
  tilt.add(rim);

  // land dots
  const dots = (landDots as { dots: number[] }).dots;
  const count = dots.length / 2;
  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const palette = DOT_COLORS.map((c) => new THREE.Color(c));
  const lime = new THREE.Color(DOT_LIME);
  const landVecs: THREE.Vector3[] = [];
  for (let i = 0; i < count; i++) {
    const v = latLngToVec3(dots[i * 2] / 10, dots[i * 2 + 1] / 10, R);
    landVecs.push(v);
    positions.set([v.x, v.y, v.z], i * 3);
    const c = seeded(i) < 0.045 ? lime : palette[Math.floor(seeded(i * 7 + 3) * palette.length)];
    colors.set([c.r, c.g, c.b], i * 3);
  }
  const dotGeo = new THREE.BufferGeometry();
  dotGeo.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  dotGeo.setAttribute("color", new THREE.BufferAttribute(colors, 3));
  // custom points shader: disc sprite drawn in-shader, faded by the same
  // screen-fixed light as the sphere so the shadowed side melts into it
  const dotMat = new THREE.ShaderMaterial({
    transparent: true,
    vertexColors: true,
    uniforms: {
      uSize: { value: 0.031 },
      uScale: { value: 300 }, // device px factor, set for real in resize()
      uLight: { value: LIGHT_DIR },
    },
    vertexShader: `
      uniform float uSize;
      uniform float uScale;
      uniform vec3 uLight;
      varying vec3 vColor;
      varying float vLight;
      void main() {
        vColor = color;
        vec4 mv = modelViewMatrix * vec4(position, 1.0);
        vec3 n = normalize(normalMatrix * position);
        vLight = mix(0.22, 1.0, clamp(dot(n, uLight), 0.0, 1.0));
        gl_PointSize = uSize * uScale / -mv.z;
        gl_Position = projectionMatrix * mv;
      }
    `,
    fragmentShader: `
      varying vec3 vColor;
      varying float vLight;
      void main() {
        float d = length(gl_PointCoord - 0.5);
        float a = smoothstep(0.5, 0.36, d);
        if (a < 0.4) discard;
        gl_FragColor = vec4(vColor, a * vLight);
        #include <colorspace_fragment>
      }
    `,
  });
  spin.add(new THREE.Points(dotGeo, dotMat));

  // ---- arcs -------------------------------------------------------------
  const arcs: Arc[] = [];
  let now = performance.now();

  function randomLandPoint() {
    return landVecs[Math.floor(Math.random() * landVecs.length)];
  }

  // traffic mirrors where Azerit is used: mostly Europe and North America,
  // with the occasional line to the rest of the world
  const euCenter = latLngToVec3(50, 12, R);
  const naCenter = latLngToVec3(42, -95, R);
  const euPoints = landVecs.filter((v) => v.angleTo(euCenter) < 0.3);
  const naPoints = landVecs.filter((v) => v.angleTo(naCenter) < 0.42);

  function pickArcPoint() {
    const r = Math.random();
    if (r < 0.4 && euPoints.length) {
      return euPoints[Math.floor(Math.random() * euPoints.length)];
    }
    if (r < 0.76 && naPoints.length) {
      return naPoints[Math.floor(Math.random() * naPoints.length)];
    }
    return randomLandPoint();
  }

  // delayRange staggers the draw start: wide on first build so the initial
  // volley doesn't fire all at once, short on respawns.
  function buildArc(arc: Arc | null, delayRange: number): Arc {
    let a = pickArcPoint();
    let b = pickArcPoint();
    for (let tries = 0; tries < 20; tries++) {
      const ang = a.angleTo(b);
      if (ang > 0.28 && ang < 2.3) break; // floor low enough for intra-Europe hops
      b = pickArcPoint();
    }
    // control point height; the curve peaks at roughly half of this above the
    // surface, so these values give visibly ballooning trajectories
    const altitude = R * (0.35 + 0.8 * (a.angleTo(b) / Math.PI));
    const mid = a.clone().add(b).normalize().multiplyScalar(R + altitude);
    const curve = new THREE.QuadraticBezierCurve3(a, mid, b);
    const geo = new THREE.TubeGeometry(curve, ARC_SEGMENTS, 0.004, 6);
    const color = new THREE.Color(ARC_COLORS[Math.floor(Math.random() * ARC_COLORS.length)]);

    if (arc) {
      arc.mesh.geometry.dispose();
      arc.mesh.geometry = geo;
      arc.mesh.material.color = color;
    } else {
      const mesh = new THREE.Mesh(
        geo,
        new THREE.MeshBasicMaterial({ color, transparent: true, opacity: 0.85 })
      );
      spin.add(mesh);
      arc = {
        mesh,
        pulses: [],
        a,
        b,
        start: 0,
        draw: 0,
        hold: 0,
        erase: 0,
        gap: 0,
        startPulsed: false,
        endPulsed: false,
      };
    }
    arc.a = a;
    arc.b = b;
    arc.start = now + Math.random() * delayRange;
    arc.draw = 1500 + Math.random() * 1000;
    arc.hold = 600 + Math.random() * 800;
    arc.erase = 1200 + Math.random() * 800;
    arc.gap = 600 + Math.random() * 1800;
    arc.startPulsed = false;
    arc.endPulsed = false;
    arc.mesh.geometry.setDrawRange(0, reduced ? ARC_INDEX_COUNT : 0);
    return arc;
  }

  const pulseGeo = new THREE.RingGeometry(0.55, 0.75, 24);
  function spawnPulse(arc: Arc, at: THREE.Vector3) {
    if (reduced) return;
    const mesh = new THREE.Mesh(
      pulseGeo,
      new THREE.MeshBasicMaterial({
        color: arc.mesh.material.color,
        transparent: true,
        opacity: 0.55,
        side: THREE.DoubleSide,
        depthWrite: false,
      })
    );
    mesh.position.copy(at).multiplyScalar(1.002);
    mesh.lookAt(at.clone().multiplyScalar(2));
    mesh.scale.setScalar(0.001);
    mesh.userData.born = now;
    spin.add(mesh);
    arc.pulses.push(mesh);
  }

  function stepPulses(arc: Arc) {
    for (let i = arc.pulses.length - 1; i >= 0; i--) {
      const p = arc.pulses[i];
      const t = (now - p.userData.born) / 1400;
      if (t >= 1) {
        spin.remove(p);
        p.material.dispose();
        arc.pulses.splice(i, 1);
      } else {
        p.scale.setScalar(0.001 + t * 0.075);
        p.material.opacity = 0.55 * (1 - t);
      }
    }
  }

  const ease = (t: number) => t * t * (3 - 2 * t);
  // snap to whole triangles so drawRange never cuts one mid-primitive
  const tri = (n: number) => n - (n % 3);

  function stepArc(arc: Arc) {
    stepPulses(arc);
    const t = now - arc.start;
    if (t < 0) return;
    const geo = arc.mesh.geometry;
    if (t < arc.draw) {
      if (!arc.startPulsed) {
        arc.startPulsed = true;
        spawnPulse(arc, arc.a);
        fireBeam(arc.a, arc.mesh.material.color);
      }
      geo.setDrawRange(0, tri(Math.floor(ARC_INDEX_COUNT * ease(t / arc.draw))));
    } else if (t < arc.draw + arc.hold) {
      geo.setDrawRange(0, ARC_INDEX_COUNT);
      if (!arc.endPulsed) {
        arc.endPulsed = true;
        spawnPulse(arc, arc.b);
        fireBeam(arc.b, arc.mesh.material.color);
      }
    } else if (t < arc.draw + arc.hold + arc.erase) {
      const from = tri(Math.floor(ARC_INDEX_COUNT * ease((t - arc.draw - arc.hold) / arc.erase)));
      geo.setDrawRange(from, ARC_INDEX_COUNT - from);
    } else if (t > arc.draw + arc.hold + arc.erase + arc.gap) {
      buildArc(arc, 400);
    } else {
      geo.setDrawRange(0, 0);
    }
  }

  for (let i = 0; i < ARC_COUNT; i++) arcs.push(buildArc(null, 3500));

  // ---- light beams ------------------------------------------------------
  // thin pillars of light rising from random land points, github.com style:
  // grow out along the surface normal, hold, retract, respawn elsewhere.
  type Beam = {
    mesh: THREE.Mesh<THREE.CylinderGeometry, THREE.MeshBasicMaterial>;
    tip: THREE.Mesh<THREE.SphereGeometry, THREE.MeshBasicMaterial>;
    dir: THREE.Vector3;
    born: number;
    grow: number;
    hold: number;
    fade: number;
    gap: number;
    maxLen: number;
  };
  const beamTex = makeBeamTexture();
  const beamGeo = new THREE.CylinderGeometry(0.0055, 0.0055, 1, 6, 1, true);
  beamGeo.translate(0, 0.5, 0); // base at origin so scale.y stretches outward
  const tipGeo = new THREE.SphereGeometry(0.0065, 8, 8);
  const beams: Beam[] = [];
  const up = new THREE.Vector3(0, 1, 0);

  if (!reduced) {
    for (let i = 0; i < BEAM_COUNT; i++) {
      const mesh = new THREE.Mesh(
        beamGeo,
        new THREE.MeshBasicMaterial({
          map: beamTex,
          transparent: true,
          opacity: 0,
          depthWrite: false,
          side: THREE.DoubleSide,
        })
      );
      mesh.scale.set(1, 0.001, 1);
      spin.add(mesh);
      const tip = new THREE.Mesh(
        tipGeo,
        new THREE.MeshBasicMaterial({ color: BEAM_TIP, transparent: true, opacity: 0, depthWrite: false })
      );
      spin.add(tip);
      beams.push({
        mesh,
        tip,
        dir: new THREE.Vector3(0, 1, 0),
        born: -1, // inactive
        grow: 0,
        hold: 0,
        fade: 0,
        gap: 0,
        maxLen: 0.2,
      });
    }
  }

  // beams only fire where arcs depart and land (called from stepArc)
  function fireBeam(at: THREE.Vector3, color: THREE.Color) {
    let beam: Beam | undefined;
    for (const b of beams) {
      if (b.born < 0) {
        beam = b;
        break;
      }
      if (!beam || b.born < beam.born) beam = b; // all busy: recycle the oldest
    }
    if (!beam) return; // reduced motion: empty pool
    beam.mesh.position.copy(at);
    beam.dir.copy(at).normalize();
    beam.mesh.quaternion.setFromUnitVectors(up, beam.dir);
    beam.mesh.material.color.copy(color);
    // squared random: mostly short pillars, occasionally a tall spike
    beam.maxLen = 0.07 + Math.random() * Math.random() * 0.3;
    beam.grow = 450 + Math.random() * 400;
    beam.hold = 1200 + Math.random() * 1600;
    beam.fade = 900 + Math.random() * 700;
    beam.born = now;
  }

  const easeOut = (t: number) => 1 - (1 - t) * (1 - t);

  function stepBeam(beam: Beam) {
    if (beam.born < 0) return;
    const t = now - beam.born;
    const m = beam.mesh;
    if (t < beam.grow) {
      m.scale.y = Math.max(0.001, beam.maxLen * easeOut(t / beam.grow));
      m.material.opacity = 0.85 * Math.min(1, t / 150);
    } else if (t < beam.grow + beam.hold) {
      m.scale.y = beam.maxLen;
      m.material.opacity = 0.85;
    } else if (t < beam.grow + beam.hold + beam.fade) {
      const u = (t - beam.grow - beam.hold) / beam.fade;
      m.scale.y = Math.max(0.001, beam.maxLen * (1 - ease(u)));
      m.material.opacity = 0.85 * (1 - u);
    } else {
      m.scale.y = 0.001;
      m.material.opacity = 0;
      beam.born = -1; // back to the pool until the next arc fires
    }
    beam.tip.position.copy(m.position).addScaledVector(beam.dir, m.scale.y);
    beam.tip.material.opacity = m.material.opacity;
  }

  // ---- interaction ------------------------------------------------------
  let dragging = false;
  let lastX = 0;
  let lastY = 0;
  let spinVel = 0; // extra rad/s from drag inertia
  const canvas = renderer.domElement;
  canvas.style.touchAction = "pan-y"; // horizontal drag spins, vertical still scrolls

  const onPointerDown = (e: PointerEvent) => {
    dragging = true;
    lastX = e.clientX;
    lastY = e.clientY;
    canvas.setPointerCapture(e.pointerId);
    container.classList.add("dragging");
  };
  const onPointerMove = (e: PointerEvent) => {
    if (!dragging) return;
    const dx = e.clientX - lastX;
    const dy = e.clientY - lastY;
    lastX = e.clientX;
    lastY = e.clientY;
    spin.rotation.y += dx * 0.005;
    tilt.rotation.x = THREE.MathUtils.clamp(tilt.rotation.x + dy * 0.003, -MAX_TILT, MAX_TILT);
    spinVel = dx * 0.005 * 60;
    if (reduced) render();
  };
  const onPointerUp = () => {
    dragging = false;
    container.classList.remove("dragging");
  };
  canvas.addEventListener("pointerdown", onPointerDown);
  window.addEventListener("pointermove", onPointerMove);
  window.addEventListener("pointerup", onPointerUp);
  window.addEventListener("pointercancel", onPointerUp);

  // ---- sizing -----------------------------------------------------------
  const resize = () => {
    const w = container.clientWidth;
    const h = container.clientHeight;
    if (!w || !h) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    renderer.setPixelRatio(dpr);
    renderer.setSize(w, h);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    dotMat.uniforms.uScale.value = (h * dpr) / 2; // keeps dot px size ∝ canvas size
    if (reduced) render();
  };
  const ro = new ResizeObserver(resize);
  ro.observe(container);
  resize();

  // ---- loop -------------------------------------------------------------
  let raf = 0;
  let visible = true;
  let last = performance.now();

  const frame = (t: number) => {
    raf = requestAnimationFrame(frame);
    const dt = Math.min((t - last) / 1000, 0.1); // clamp tab-restore jumps
    last = t;
    now = t;
    if (!dragging) {
      spinVel *= Math.pow(0.05, dt); // inertia decays back toward auto spin
      spin.rotation.y += (AUTO_SPIN + spinVel) * dt;
    }
    for (const arc of arcs) stepArc(arc);
    for (const beam of beams) stepBeam(beam);
    render();
  };

  const start = () => {
    if (!raf && visible && !reduced) {
      last = performance.now();
      raf = requestAnimationFrame(frame);
    }
  };
  const stop = () => {
    cancelAnimationFrame(raf);
    raf = 0;
  };

  // don't burn frames while the hero is scrolled away
  const io = new IntersectionObserver(([entry]) => {
    visible = entry.isIntersecting;
    visible ? start() : stop();
  });
  io.observe(container);

  if (reduced) {
    render(); // single static frame; drag/resize re-render on demand
  } else {
    start();
  }

  return () => {
    stop();
    io.disconnect();
    ro.disconnect();
    canvas.removeEventListener("pointerdown", onPointerDown);
    window.removeEventListener("pointermove", onPointerMove);
    window.removeEventListener("pointerup", onPointerUp);
    window.removeEventListener("pointercancel", onPointerUp);
    for (const arc of arcs) {
      arc.mesh.geometry.dispose();
      arc.mesh.material.dispose();
      for (const p of arc.pulses) p.material.dispose();
    }
    for (const beam of beams) {
      beam.mesh.material.dispose();
      beam.tip.material.dispose();
    }
    beamGeo.dispose();
    tipGeo.dispose();
    beamTex.dispose();
    pulseGeo.dispose();
    dotGeo.dispose();
    dotMat.dispose();
    rim.geometry.dispose();
    rimMat.dispose();
    sphere.geometry.dispose();
    sphereMat.dispose();
    renderer.dispose();
    container.removeChild(canvas);
  };
}
